name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Stop old app if running
        run: |
          PID=$(sudo lsof -t -i:8080 || true)
          if [ -n "$PID" ]; then
            echo "Stopping old app (PID: $PID)"
            sudo kill -9 $PID
          else
            echo "No app running on port 8080"
          fi

      - name: Start new app
        run: |
          nohup java -jar ~/actions-runner/_work/ci-cd-demo/ci-cd-demo/target/ci-cd-demo-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          sleep 5
          echo "App restarted"
